### ISSUE TITLE
Access to undeclared static property Emrebbozkurt\VerimorSms\VerimorService::$to

### ISSUE THREAD

**Issue by OrhanOzyalcin** [emrebbozkurt/laravel-verimor-sms#2]
Merhabalar,  örnekte  olduğu gibi send metodu kullanmaya çalışıldığında sistemin verdiği hata: 

`Access to undeclared static property Emrebbozkurt\VerimorSms\VerimorService::$to`

Ayrıca emeklerin için teşekkürler @emrebbozkurt 

Ek: config app.php içine service provider tanımlamaya çalıştım orada da hata aynıydı.

**Comment by bozkurtemre** [comment]
Merhabalar @OrhanOzyalcin,

Öncelikle geri bildirimin için çok teşekkür ederim gerekli güncellemeyi yaptım ve aynı zamanda Laravel 10 için destek ekledim.
(6bb6085ae6aca8be0ccbb026ba42c8fb985b6bb6)

**Comment by OrhanOzyalcin** [comment]
Teşekkürler,  denemesini yapıp bilgi vereceğim.
